baseURL = "https://wtfutil.com/"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false
languageCode = "en-us"
publishDir = "./docs"
theme = "ace-documentation"
title = "WTF - the terminal dashboard"

[params]
editURL = "https://github.com/vjeantet/hugo-theme-docdock/edit/master/exampleSite/content/"
showVisitedLinks = true # default is false
themeStyle = "flex" # "original" or "flex" # default "flex"
themeVariant = "" # choose theme variant "green", "gold" , "gray", "blue" (default)
ordersectionsby = "weight" # ordersectionsby = "title"
disableHomeIcon = false # default is false
disableSearch = false # default is false
disableNavChevron = false # set true to hide next/prev chevron, default is false
highlightClientSide = false # set true to use highlight.pack.js instead of the default hugo chroma highlighter
menushortcutsnewtab = false # set true to open shortcuts links to a new tab/window
enableGitInfo = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
unsafe= true

[[menu.shortcuts]]
pre = "<h3>More</h3>"
name = "<i class='fab fa-github'>&nbsp;</i> <label>WTF on Github</label>"
identifier = "ds"
url = "https://github.com/wtfutil/wtf"
weight = 10

[[menu.shortcuts]]
name = "<i class='fa fa-cloud-download-alt'></i> <label>Download WTF</label>"
url = "https://github.com/wtfutil/wtf/releases"
weight = 20

[[menu.shortcuts]]
name = "<i class='fa fa-bullhorn'></i> <label>Credits</label>"
url = "https://github.com/wtfutil/wtf/blob/master/README.md#contributors"
weight = 30

[[menu.shortcuts]]
name = "<i class='fas fa-blog'>&nbsp;</i> <label>Blog</label>"
url = "/blog"
weight = 40
